In [1]:
import numpy as np
import math

In [2]:
# User created function Function
def magnitude(vector):
    coords_squared = tuple([x**2 for x in vector])
    result = math.sqrt(sum(coords_squared))
    return result
#Example
magnitude(np.array([1,2]))

2.23606797749979

In [3]:
def Angle_between_vectors(vector1, vector2):
    mag_vec1 = magnitude(vector1)
    mag_vec2 = magnitude(vector2)
    print(f'Vector1 magnitude: {round(mag_vec1,2)}')
    print(f'Vector2 magnitude: {round(mag_vec2,2)}')
    inner_product = np.dot(vector1, vector2)
    print(f'Inner product of vectors: {inner_product}')
    angle_rad = math.acos((inner_product/ (mag_vec1*mag_vec2)))
    degrees_per_radian = 180/math.pi
    solution = angle_rad* degrees_per_radian
    print(f'Angle between vector 1 & 2 is: {round(solution,2)}°')
#Example
Angle_between_vectors([-8,1],[-2,7])

Vector1 magnitude: 8.06
Vector2 magnitude: 7.28
Inner product of vectors: 23
Angle between vector 1 & 2 is: 66.93°


In [4]:
def unit_vector(vector):
    coords_squared = tuple([x**2 for x in vector])
    magnitude = math.sqrt(sum(coords_squared))
    normalized = (1/magnitude)
    unit_vector = np.multiply(vector, normalized)
    return unit_vector
#Example
unit_vector(np.array([1,2]))

array([0.4472136 , 0.89442719])

In [5]:
def projection_length(line, x_vec):
    unit = unit_vector(line)
    equation = (np.dot(x,unit))*unit
    return equation

#Example
line = np.array([2,1])
x = np.array([2,3])
projection_length(line, x)

array([2.8, 1.4])

In [6]:
#Function to solve subspace projection matrix
def subspace_projection(matrix):
    A = matrix
    A_trans = matrix.T
    inverse = np.linalg.inv(np.dot(A_trans,A))
    A_dot_inv = np.dot(A, inverse)
    A_dot_inv_dot_Atrans = np.dot(A_dot_inv, A_trans)
    return A_dot_inv_dot_Atrans

#Example
A = np.array([[1,0],[0,1],[0,0],[1,1]])
subspace_projection(A)

array([[ 0.66666667, -0.33333333,  0.        ,  0.33333333],
       [-0.33333333,  0.66666667,  0.        ,  0.33333333],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.33333333,  0.33333333,  0.        ,  0.66666667]])

In [7]:
def invertible_change_basis(vec_a, change_basis_matrix):
    c_inv = np.linalg.inv(change_basis_matrix)
    print('Change of basis matrix inverted:')
    print(c_inv)
    coordinates_wrt_basis_b = np.dot(c_inv, a)
    print('Coordinates of input vector w.r.t. basis matrix:')
    print(coordinates_wrt_basis_b)

#Example
c = np.matrix([[1,2],[3,1]])
a = np.array([7,2])
invertible_change_basis(a, c)

Change of basis matrix inverted:
[[-0.2  0.4]
 [ 0.6 -0.2]]
Coordinates of input vector w.r.t. basis matrix:
[[-0.6  3.8]]


In [8]:
def alternate_basis_transform(transformation_matrix, alternate_basis):
    #D= C^{-1}AC
    c = alternate_basis
    c_inv = np.linalg.inv(alternate_basis)
    print('Change of basis matrix inverted:')
    print(c_inv)
    d_equals = np.dot(c_inv, np.dot(transformation_matrix, alternate_basis)) # C^-1 * A* C
    print('D transformation w.r.t to alternate basis:')
    print(d_equals)
    
#Example

A = np.matrix([[3,-2],[2,-2]])
B = np.matrix([[1,2],[2,1]])
alternate_basis_transform(A,B)

Change of basis matrix inverted:
[[-0.33333333  0.66666667]
 [ 0.66666667 -0.33333333]]
D transformation w.r.t to alternate basis:
[[-1.  0.]
 [ 0.  2.]]
